services:
  redis-prod:
    image: redis:7-alpine
    container_name: excel-redis-prod
    ports:
      - "36379:6379"
    volumes:
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/db/redis/redis-data:/data
    command: redis-server --appendonly yes # AOF 방식 영속화
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-prod:
    image: postgres:15-alpine
    container_name: excel-postgres-prod
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: ec_db
      POSTGRES_USER: ec_user
      POSTGRES_PASSWORD: ec_pwd
    volumes:
      - ~/docker/postgres-data:/var/lib/postgresql/data  # WSL 홈 디렉토리에 마운트. /mnt/c/ 는 chmod 불가로 마운트 불가
    networks:
      - prod-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ec_user -d ec_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Applications
  app1:
    build: .
    container_name: excel-app-1
    ports:
      - "8082:8080"
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    restart: on-failure
    networks:
      - prod-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-prod:5432/ec_db
      SPRING_DATA_REDIS_HOST: redis-prod
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 8080
      HOSTNAME: app1
    volumes:
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/apps/app1/downloads:/app/downloads
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/apps/app1/tmp:/tmp

  app2:
    build: .
    container_name: excel-app-2
    ports:
      - "8083:8080"
    depends_on:
      postgres-prod:
        condition: service_healthy
      redis-prod:
        condition: service_healthy
    networks:
      - prod-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-prod:5432/ec_db
      SPRING_DATA_REDIS_HOST: redis-prod
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 8080
      HOSTNAME: app2
    volumes:
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/apps/app2/downloads:/app/downloads
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/apps/app2/tmp:/tmp

  nginx-prod:
    image: nginx:alpine
    container_name: excel-nginx-prod
    ports:
      - "8090:80"
    restart: on-failure  # 실패 시 재시작
    depends_on:
      - app1
      - app2
    volumes:
      - /mnt/c/APPS/PROJECTS/0_PRACTICE/excel-optimizer/docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - prod-network


networks:
  prod-network:
    name: excel-prod-network
    driver: bridge

#volumes:
#  redis-data: